In [ ]:
Pre-Processing Data 
1. Create dummy variable for our categorical variables 
2. make sure we have our numerical data 
3. Create our training and test data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import os 
import numpy as np 
import seaborn as sns 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

energy_df = pd.read_csv('../data/raw/2012_data.csv' , index_col = 0)

In [3]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1296 entries, 0.98 to nan
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X2      768 non-null    float64
 1   X3      768 non-null    float64
 2   X4      768 non-null    float64
 3   X5      768 non-null    float64
 4   X6      768 non-null    float64
 5   X7      768 non-null    float64
 6   X8      768 non-null    float64
 7   Y1      768 non-null    float64
 8   Y2      768 non-null    float64
dtypes: float64(9)
memory usage: 101.2 KB

In [4]:
energy_df.head()

         X2     X3      X4   X5   X6   X7   X8     Y1     Y2
X1
0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

energy_df = pd.read_csv('../data/raw/2012_data.csv' , index_col = 0)

energy_data = { 
    'Column 1': [ 1,2,'Missing', 4],
    'Column 2':['Missing','Data','Missing','Vaule'],
    'Column 3':[ 5,6,7,8]

}

energy_df = pd.DataFrame(energy_data)

energy_columns = list(energy_df.columns)

missing = [sum(energy_df[column] == 'Missing') for column in energy_df]

energy_missing = pd.DataFrame(data=missing, index=energy_columns, columns=['Missing_Count'])
energy_missing

          Missing_Count
Column 1              1
Column 2              2
Column 3              0

In [19]:
energy_df['Column 2'] = energy_df['Column 2'].fillna('Not Available')

energy_df

  Column 1 Column 2  Column 3
0        1  Missing         5
1        2     Data         6
2  Missing  Missing         7
3        4    Vaule         8

In [20]:
energy_df = pd.DataFrame(energy_data)


energy_df.drop(['Column 2'], axis = 1)
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column 1  4 non-null      object
 1   Column 2  4 non-null      object
 2   Column 3  4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [10]:
#Replace the string "Missing" with type NaN so we can replace data
energy_df = energy_df.replace('Missing', np.nan)
energy_df.isna().sum()

Column 1    1
Column 2    2
Column 3    0
dtype: int64

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

energy_df = pd.read_csv('../data/raw/2012_data.csv' , index_col = 0)

energy_df = pd.DataFrame(energy_data)

energy_df['Column 3'] = pd.to_numeric(energy_df['Column 3'])
energy_df['Column 3'] = energy_df['Column 3'].fillna(energy_df['Column 3'].mode()[0])

In [12]:
energy_df.isna().sum()

Column 1    0
Column 2    0
Column 3    0
dtype: int64

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

energy_df = pd.read_csv('../data/raw/2012_data.csv' , index_col = 0)



energy_cat = energy_df.select_dtypes(include = 'object').columns 
energy_df.insert(0 , '','')
energy_df

            X2     X3      X4   X5   X6   X7   X8     Y1     Y2
X1
0.98     514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
0.98     514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
0.98     514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
0.98     514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
0.90     563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28
...  ..    ...    ...     ...  ...  ...  ...  ...    ...    ...
NaN        NaN    NaN     NaN  NaN  NaN  NaN  NaN    NaN    NaN
NaN        NaN    NaN     NaN  NaN  NaN  NaN  NaN    NaN    NaN
NaN        NaN    NaN     NaN  NaN  NaN  NaN  NaN    NaN    NaN
NaN        NaN    NaN     NaN  NaN  NaN  NaN  NaN    NaN    NaN
NaN        NaN    NaN     NaN  NaN  NaN  NaN  NaN    NaN    NaN

[1296 rows x 10 columns]

In [21]:
energy_dummies = pd.get_dummies(energy_df, columns = energy_cat, drop_first = True)
energy_dummies.head()

           X2     X3      X4   X5   X6   X7   X8     Y1     Y2
X1
0.98    514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
0.98    514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
0.98    514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
0.98    514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
0.90    563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28

In [33]:
df = energy_dummies 
df['Binarize  X7'] = 0 
df.loc[df['X7'] > 0, 'Binarize_X7'] = 1

X7

In [75]:
df = df.drop('Binarize_X7', axis = 1)

KeyError: "['Binarize_X7'] not found in axis"

In [53]:
df = df.drop('Binarize Column 3', axis = 1)

In [84]:
df.drop ('X7')

KeyError: "['X7'] not found in axis"

In [89]:
df.drop('Binarize_X7', axis = 0)

KeyError: "['Binarize_X7'] not found in axis"